### PR TITLE
fix fvar axis/instance name parsing and writing (fix #687)

### LINKED ISSUE #687: fvar.instances returns empty name entry if nameID is 17 (preferredSubfamily)
In the name table, the preferredSubfamily name is set in nameID 17. In exports from the Glyphs font editor, the fvar table references this entry for the default variable font instance. However, opentype.js returns an empty name entry for this instance when listing the fvar instances.

## Expected Behavior
fvar.instances should return a name entry for the default instance (which often has nameID 17 as its corresponding name entry).

## Current Behavior
Currently, fvar.instances returns, for example, {"name":{},"coordinates":{"wght":100,"ital":0}} if the nameID for that fvar instance is 17.

## Possible Solution
I assume the nameID 17 is, at some point, automatically replaced by a "preferredSubfamily" identifier, thus returning undefined when being searched for in the name table. This should not be done. The name IDs should be read as they are from the fvar table and then referenced in the name table.

## Steps to Reproduce (for bugs)
Export a variable font from the latest Glyphs version and check its fvar instances. Alternatively, get a variable font trial from abcdinamo.com (for example), such as Arizona, and check its fvar instances.

## Context
I have been trying to list all instance names of a variable font, by getting the name table entries from the fvar instance list. However, I get an empty entry for the name of the default instance.

## Your Environment
* Version used: 1.3.4
* Font used: Arizona Serif Variable
* Browser Name and version: irrelevant
* Operating System and version (desktop or mobile): irrelevant
* Link to your project: irrelevant

### PR DESCRIPTION
**Pull request by Connum**
## Description

Fixes parsing of name IDs in the fvar table (fix #687) and adds parsing/optional writing of the postScriptNameID field.
I also refactored name handling a bit. Having the fvar make function modify the name table by creating new entries (without checking if a name entry already existed) was a bad design choice and shouldn't be done during writing anyway, so I removed the `addName()` function completely. New names should be added to the name tables and then be referenced by ID in the fvar table. When we add "comfort" functions to the variable features later, these should handle this accordingly, but for now this has to be done manually.

## Motivation and Context

Parsing the names for axes/instances in the fvar table did not work correctly in all cases. Name ID values 2 and 17 for the instance name, as well as 6 for the postScriptNameID were not parsed correctly (and postScriptNameID was so far not parsed at all). These are allowed according to the spec:
* https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#:~:text=Values%20of%202%20or%2017%20can%20be%20used
* https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#:~:text=Values%20of%206%20and%200xFFFF%20can%20be%20used

## How Has This Been Tested?

Test font provided in #687 and additional tests created.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I did `npm run test` and all tests passed green (including code styling checks).
- [X] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by eweracs** [comment]
Thanks a lot, Constantin! This is a rather crucial fix for a serious bug, is there some way this could be reviewed in the near future?

**Comment by Connum** [comment]
> is there some way this could be reviewed in the near future?

I hope so! Pinging @yne @ILOVEPIE

**Review by yne — COMMENTED** [review]
thanks @Connum 💪

**Comment by Connum** [comment]
Rebased onto current master, needs another review to be able to merge

**Comment by Connum** [comment]
Oh boy, the rebase broke something... I'll have a look at it later.

**Comment by Connum** [comment]
@yne ready for final review

**Review by yne — APPROVED** [review]

**Pull request merged**
