### PR TITLE
Support in path.draw() for an options parameter that allows stroking the text first before filling

### PR DESCRIPTION
**Pull request by ophinjay**
## Description
In the current implementation, `path.draw()` only accepts canvas context and it always fills the text first and then strokes it(if enabled). The PR proposes a second parameter to be passed to `path.draw()` called `options`. `options.strokeFirst` will be `false` by default and will cause the path to be filled first and then stroked(as is the current behavior). If `true`, it will stroke the path first and then fill it.

## Motivation and Context
The current approach works well if the canvas context does not have shadows enabled. If shadows have been enabled using the shadow properties - `shadowOffsetX`, `shadowOffsetY`, `shadowColor` and `shadowBlur`, the current implementation results in an inner shadow(as shown in screenshot 1). To get an outer shadow, it is required to stroke the text first and then fill(as shown in screenshot 2). 

## How Has This Been Tested?
The code was tested with both fill and stroke enabled in all cases

### 1. Without shadows in canvas context
 - Text was rendered without the `options` property and the glyph rendered properly in accordance with the current implementation
 - Text was rendered with `options.strokeFirst` as `false` and the glyph rendered properly in accordance with the current implementation
 - Text was rendered with `options.strokeFirst` as `true` and the glyph rendered properly in accordance with the current implementation

### 2. With shadows in canvas context
 - Text was rendered without the `options` property and the glyph rendered with inset shadows in accordance with the current implementation
 - Text was rendered with `options.strokeFirst` as `false` and the glyph rendered with inset shadows in accordance with the current implementation
 - Text was rendered with `options.strokeFirst` as `true` and the glyph rendered with outset shadows as expected

## Screenshots:
[Screenshot 1](https://media.kubric.io/api/assetlib/1c919628-5279-4a92-98dd-c622b4cb0458.png)
[Screenshot 2](https://media.kubric.io/api/assetlib/167285ed-b9bb-4c0e-93c2-5dfe2f5f1620.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the **README** accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Connum** [comment]
I create PR https://github.com/cirbuk/opentype.js/pull/1 on the feature branch to get this reviewed and merged

**Comment by Connum** [comment]
@ophinjay could you please merge in my PR? We might have to resolve some more conflicts after that...

**Comment by Connum** [comment]
Closing as there appears to be no interest in getting this merged.

**Comment by ILOVEPIE** [comment]
I am interested in getting this merged but I've been a little busy so I
haven't been able to do any review or anything.

**Pull request closed without merging**
