### PR TITLE
Add version performance benchmark tool

### PR DESCRIPTION
**Pull request by yne**
## Description

This PR add a per-version performance comparison tool.

## Motivation and Context

This tool will help us quantify performance gain/loss between the current /src/ build and the last master build (or any previous version built).

## How Has This Been Tested?
Tested on `npm start` and opening `/docs/benchmark.html` on chromium 

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Connum** [comment]
Good idea, but I think instead of just parsing a file, we should also let it render some text, because I think that's where we should really see a decrease in performance when more features are added. I'll just leave my test script here that I wrote for testing the `forEach()`/`for()` performance:

```js
const textToRender = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ffffiThe king said: เป็นคนใจดีสำหรับทุกคน because ความรักคือทุกสิ่ง ลลฤๅ'.repeat(10);
const loopCount = 100;

const fileButton = document.getElementById('file');
fileButton.addEventListener('change', onReadFile, false);

let addedTime = 0;
let loopsOutstanding = loopCount;
let errTries = 0;

function onReadFile(e) {
    const file = e.target.files[0];
    const reader = new FileReader();
    reader.onload = function(e) {
        for(let i = 0; i < loopCount; i++) {
            const start = performance.now();
            font = opentype.parse(e.target.result);
            const glyphs = font.stringToGlyphs(textToRender);
            for (let i = 0; i < glyphs.length; i++) {
                const glyph = glyphs[i];
                glyph.path.toSVG();
            }
            const duration = performance.now() - start;
            const msg = 'Execution time: ' + duration + 'ms';
            console.log(msg, loopsOutstanding);
            output.textContent = msg;
            addedTime+=duration;
            loopsOutstanding--;

            if (loopsOutstanding === 0) {
                const finalMsg = 'Average execution time: ' + (addedTime / loopCount) + 'ms';
                console.log(finalMsg);
                output.textContent = finalMsg;
            }
        };
    }
    reader.onerror = function(e) {
        errors.innerHTML += '<br>' + e.currentTarget.error;
        errTries++;
        if (errTries < 100) {
            reader.readAsArrayBuffer(file);
        } else {
            errors.innerHTML += '<br><strong>ABORTED</strong>';
        }
    }
    reader.readAsArrayBuffer(file);
}
```

**Comment by yne** [comment]
I'll add your code to the benchmark 👍

**Comment by yne** [comment]
@Connum [stringToGlyphs + toSVG](https://github.com/opentypejs/opentype.js/compare/a903fcee97616da266501dae8656b137e1d47e7c..91d9079193f6aa8bf4c22fc0e393bb4a8746719a) added

We can now clearly see a performance drop between
- 1.3.4 : 1377.9ms
- master : 5576.9ms (8265.3ms with `optimize:true`)

**Comment by Connum** [comment]
Interesting! A lot of features and fixes have been introduced since 1.3.4 and each table support we add increases parsing time. Maybe we should add more options to skip features that may not always be required. We should try to find out which features have the most impact on performance.

**Comment by Connum** [comment]
I found the culprit for the performance decrease to be `roundDecimal()` in `path.js`. This should be improved before releaseing 2.0.0, I'm going to open an issue for this.
This benchmark tool made it way easier to test that, let's add it as-it-is and make improvements with time.

**Review by Connum — APPROVED** [review]

**Pull request merged**
