### PR TITLE
mark as side effect free

### PR DESCRIPTION
**Pull request by hipstersmoothie**
## Description

Marked the package as side effect free so it can be tree shaken by webpack if not used

## Motivation and Context

I saw that this package was included in my bundle. I'm not actually sure if this dep is side effect free.... is it?

## How Has This Been Tested?

In my app

## Checklist:

- [ ] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [x] I have updated the **README** accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by ILOVEPIE** [comment]
@hipstersmoothie please rebase onto and create a pull request for the new active development fork [here](https://github.com/SABRE-JS/opentype.js)

**Comment by ILOVEPIE** [comment]
@Jolg42 is the library side-effect free, if so this is any easy change we could make.

**Comment by ILOVEPIE** [comment]
> @Jolg42 is the library side-effect free, if so this is any easy change we could make.

@Connum how about you?

**Comment by Connum** [comment]
> @Connum how about you?

Sorry, I can't provide an answer to this one. I don't have an in-depth understanding of tree shaking and side effects and I'm not deep enough into the code base yet to have an understanding of what all the different parts of the code are doing.

**Comment by me4502** [comment]
I've looked at a bunch of files, and it doesn't appear any side effects are present.

Generally what you want to look for is any instance where just the act of importing a file will trigger something to happen. So function calls, etc at the top level. Anything that just sets up a variable to be exported is fine, as that's all repeatable & doesn't modify anything aside from exported entries.

**Comment by Connum** [comment]
> I've looked at a bunch of files, and it doesn't appear any side effects are present.
> 
> Generally what you want to look for is any instance where just the act of importing a file will trigger something to happen. So function calls, etc at the top level. Anything that just sets up a variable to be exported is fine, as that's all repeatable & doesn't modify anything aside from exported entries.

Thanks for the valuable input and for looking into this. I haven't encountered anything that seems to hint at side effects while working on this library so far then. So in my opinion we can merge this.

**Review by ILOVEPIE — APPROVED** [review]
Looks good to me, as long as the library is actually side-effect free.

**Pull request merged**
