### PR TITLE
adding stringToGlyphIndexes()

### PR DESCRIPTION
**Pull request by axkibe**
## Description
adresses #574 

## How Has This Been Tested?
I tested it with my quite larger app, it works, it's quite a trivial change tough.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes. 
No I didn't, I tested it with my application.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
charToGlyphIndex() and nameToGlyphIndex() are also not mentenioned in the README, maybe we should add all?
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by yne — CHANGES_REQUESTED** [review]
@axkibe could you add a test case in `test/font.js` ?

**Comment by Connum** [comment]
I also reviewed it, other than the missing test as mentioned, it looks good to me!

**Comment by axkibe** [comment]
Ok I'll add the test tomorrow or the day after.

**Comment by axkibe** [comment]
Ok, added.

**Review by yne — APPROVED** [review]

**Pull request merged**
