### PR TITLE
Use less memory

### PR DESCRIPTION
**Pull request by debussy2k**
Font glyphs are loaded on demand. This enables consuming less heap memory. Especially opentype.js can save memory very much with CJK fonts. 

## Motivation and Context
When opentype.js load cjk fonts it uses memory 8~10 times more than font file size in worst case. It depends on number of glyphs. If I try to load NotoSansCJKkr.otf(file size : 16MB) it uses 220Mb heap memory. 

## How Has This Been Tested?
npm tested.
Test cases for low memory mode are added.

## Screenshots
Belows are the heap snapshots of Glyph Inspector page with  NotoSansCJKkr.otf(file size : 16MB).
Please look at the size of glyphs object under Font object.

Before
developer tools - https___opentype js org_glyph-inspector html 2018-03-06 6_38_19

After
developer tools - http___localhost_8080_glyph-inspector html 2018-03-06 6_36_36

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I did `npm run test` and all tests passed green (including code styling checks).
- [x] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Jolg42** [comment]
Hi @debussy2k 

Nice improvement! I will check that in detail soon!

In the meantime it looks like the Travis build has some errors like:
```
/home/travis/build/nodebox/opentype.js/src/opentype.js:169
function parseBuffer(buffer, opt={}) {
                                ^
SyntaxError: Unexpected token =
```

It's probably because your code is not compatible with Node.js v4.
The best would be to install the latest version 4 with nvm for example and fix all the errors you can find 😉

Thanks for the tests btw!

**Comment by debussy2k** [comment]
@Jolg42 , I fixed problem not to use default parameter value for node.js 4.
Thanks,

**Comment by Jolg42** [comment]
Sorry for the delay 🙏 

Link to Noto Sans CJK Regular
https://github.com/googlei18n/noto-cjk/blob/master/NotoSansCJKkr-Regular.otf

Everything looks fine for me, the gain in performance is indeed huge, good job!

Did you change anything in the implementation since your PR?

**Comment by debussy2k** [comment]
No changes have been made.

I have been testing many since my PR using my commercial products in the browser and node.js.

Anyway, happy to hear from you.

**Comment by Jolg42** [comment]
Perfect!

I tried your PR and it works well indeed! Good job 👍 

I'll merge and publish it asap 😉

**Comment by debussy2k** [comment]
If you have any problem with merging, please let me help you.

**Pull request merged**
